/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createApartment {
  about: string;
  basicPrice: number;
  bathroom: number;
  bedroom: number;
  beds: number;
  commodities: {
    has: boolean;
    name: string;
  }[];
  contacts: {
    contact_name: string;
    email?: string;
    phone: string;
  }[];
  details: {
    name: string;
    value: string;
  }[];
  kitchen: boolean;
  name: string;
  property_security: {
    name: string;
    value: string;
  }[];
  rules: {
    check_in: string;
    check_out: string;
    guests_quantity: number;
  };
  simpleLocation: string;
  type: 'Apartment' | 'Studio';
}
