/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createApartment {
  about: string;
  basicPrice: number;
  bathroom: number;
  bedroom: number;
  beds: number;
  details?: apartmentDetails[];
  kitchen: boolean;
  name: string;
  simpleLocation: string;
  type?: 'Apartment' | 'Studio';
}
